using GSDT.Notifications.Application.Commands.MarkNotificationRead;
using GSDT.Notifications.Domain.Entities;
using GSDT.Notifications.Domain.Repositories;
using GSDT.Notifications.Domain.ValueObjects;
using FluentAssertions;
using FluentResults;
using NSubstitute;

namespace GSDT.Notifications.Application.Tests.Commands;

/// <summary>
/// Unit tests for MarkNotificationReadCommandHandler.
/// Covers success, not-found, and ownership-violation paths.
/// </summary>
public sealed class MarkNotificationReadCommandHandlerTests
{
    private readonly INotificationRepository _repo = Substitute.For<INotificationRepository>();
    private readonly MarkNotificationReadCommandHandler _sut;

    private static readonly Guid TenantId = Guid.NewGuid();
    private static readonly Guid OwnerUserId = Guid.NewGuid();
    private static readonly Guid OtherUserId = Guid.NewGuid();

    public MarkNotificationReadCommandHandlerTests()
    {
        _sut = new MarkNotificationReadCommandHandler(_repo);
    }

    // --- Happy path ---

    [Fact]
    public async Task Handle_ValidOwner_ReturnsOk()
    {
        var notification = CreateNotification(OwnerUserId);
        _repo.GetByIdAsync(notification.Id, Arg.Any<CancellationToken>())
            .Returns(Result.Ok(notification));

        var command = new MarkNotificationReadCommand(notification.Id, TenantId, OwnerUserId);
        var result = await _sut.Handle(command, CancellationToken.None);

        result.IsSuccess.Should().BeTrue();
    }

    [Fact]
    public async Task Handle_ValidOwner_CallsUpdateAsync()
    {
        var notification = CreateNotification(OwnerUserId);
        _repo.GetByIdAsync(notification.Id, Arg.Any<CancellationToken>())
            .Returns(Result.Ok(notification));

        var command = new MarkNotificationReadCommand(notification.Id, TenantId, OwnerUserId);
        await _sut.Handle(command, CancellationToken.None);

        await _repo.Received(1).UpdateAsync(notification, Arg.Any<CancellationToken>());
    }

    // --- Not found ---

    [Fact]
    public async Task Handle_NotificationNotFound_ReturnsFail()
    {
        var missingId = Guid.NewGuid();
        _repo.GetByIdAsync(missingId, Arg.Any<CancellationToken>())
            .Returns(Result.Fail("not found"));

        var command = new MarkNotificationReadCommand(missingId, TenantId, OwnerUserId);
        var result = await _sut.Handle(command, CancellationToken.None);

        result.IsFailed.Should().BeTrue();
    }

    [Fact]
    public async Task Handle_NotificationNotFound_DoesNotCallUpdate()
    {
        var missingId = Guid.NewGuid();
        _repo.GetByIdAsync(missingId, Arg.Any<CancellationToken>())
            .Returns(Result.Fail("not found"));

        var command = new MarkNotificationReadCommand(missingId, TenantId, OwnerUserId);
        await _sut.Handle(command, CancellationToken.None);

        await _repo.DidNotReceive().UpdateAsync(Arg.Any<Notification>(), Arg.Any<CancellationToken>());
    }

    // --- Ownership violation ---

    [Fact]
    public async Task Handle_WrongUser_ReturnsForbiddenError()
    {
        var notification = CreateNotification(OwnerUserId);
        _repo.GetByIdAsync(notification.Id, Arg.Any<CancellationToken>())
            .Returns(Result.Ok(notification));

        // OtherUserId tries to mark OwnerUserId's notification as read
        var command = new MarkNotificationReadCommand(notification.Id, TenantId, OtherUserId);
        var result = await _sut.Handle(command, CancellationToken.None);

        result.IsFailed.Should().BeTrue();
        result.Errors.Should().ContainSingle(e => e.Message.Contains("Cannot mark another user"));
    }

    [Fact]
    public async Task Handle_WrongUser_DoesNotCallUpdate()
    {
        var notification = CreateNotification(OwnerUserId);
        _repo.GetByIdAsync(notification.Id, Arg.Any<CancellationToken>())
            .Returns(Result.Ok(notification));

        var command = new MarkNotificationReadCommand(notification.Id, TenantId, OtherUserId);
        await _sut.Handle(command, CancellationToken.None);

        await _repo.DidNotReceive().UpdateAsync(Arg.Any<Notification>(), Arg.Any<CancellationToken>());
    }

    // --- Helpers ---

    /// <summary>
    /// Creates a valid Notification aggregate via domain factory.
    /// Id is auto-generated by Notification.Create — captured for command construction.
    /// </summary>
    private static Notification CreateNotification(Guid recipientUserId) =>
        Notification.Create(
            TenantId,
            recipientUserId,
            subject: "Test Subject",
            body: "Test Body",
            channel: NotificationChannel.InApp,
            createdBy: Guid.NewGuid());
}
