import { useEffect } from 'react';
import { Form, Input, Row, Col, Button, message } from 'antd';
import { PlusOutlined } from '@ant-design/icons';
import { useNavigate } from '@tanstack/react-router';
import dayjs from 'dayjs';
import { DatePickerMaxToday, FileUploadField } from '@/features/shared/components';
import {
  useSeedCatalog,
  useDynamicCatalog,
  useCreateDomesticProject,
  useUpdateDomesticProject,
  useDomesticProject,
} from '../domestic-project-api';
import { Tab1LocationsZone } from './tab1-locations-zone';
import { Tab1DecisionsZone } from './tab1-decisions-zone';
import { Tab1Zone2Budget } from './tab1-zone2-budget';
import { Tab1Zone3Classification } from './tab1-zone3-classification';

interface Tab1Props {
  projectId: string | null;
  mode: 'create' | 'edit' | 'detail';
  onSaved?: () => void;
  onDirty?: () => void;
  /** Callback when project is created — passes new project ID to parent */
  onProjectCreated?: (id: string) => void;
}

// Tab 1: Thông tin chung — 5 zones, ~30+ fields.
// Zone 1: Basic info & policy. Zone 2: Budget. Zone 3: Classification & owner.
// Zone 4: Locations (inline table). Zone 5: Investment decisions (inline form + table).
export function Tab1GeneralInfo({ projectId, mode, onSaved, onDirty, onProjectCreated }: Tab1Props) {
  const [form] = Form.useForm();
  const navigate = useNavigate();
  const isReadonly = mode === 'detail';

  // Data queries
  const { data: project } = useDomesticProject(projectId ?? undefined);
  const { data: industrySectors = [] } = useSeedCatalog('industry-sectors');
  const { data: projectGroups = [] } = useSeedCatalog('project-groups');
  const { data: statuses = [] } = useSeedCatalog('domestic-project-statuses');
  const { data: managingAuthorities = [] } = useDynamicCatalog('managing-authorities');
  const { data: nationalTargetPrograms = [] } = useDynamicCatalog('national-target-programs');
  const { data: projectOwners = [] } = useDynamicCatalog('project-owners');
  const { data: pmus = [] } = useDynamicCatalog('project-management-units');

  // Mutations
  const createMutation = useCreateDomesticProject();
  const updateMutation = useUpdateDomesticProject();
  const saving = createMutation.isPending || updateMutation.isPending;

  // Pre-fill form on edit/detail
  useEffect(() => {
    if (project && mode !== 'create') {
      form.setFieldsValue({
        ...project,
        policyDecisionDate: project.policyDecisionDate ? dayjs(project.policyDecisionDate) : null,
        stopDecisionDate: project.stopDecisionDate ? dayjs(project.stopDecisionDate) : null,
      });
    }
  }, [project, mode, form]);

  // Auto-calculate budget fields
  const centralBudget = Form.useWatch('prelimCentralBudget', form) ?? 0;
  const localBudget = Form.useWatch('prelimLocalBudget', form) ?? 0;
  const otherPublicCapital = Form.useWatch('prelimOtherPublicCapital', form) ?? 0;
  const otherCapital = Form.useWatch('prelimOtherCapital', form) ?? 0;
  const publicInvestment = centralBudget + localBudget + otherPublicCapital;
  const totalInvestment = publicInvestment + otherCapital;

  async function handleSave() {
    let values;
    try {
      values = await form.validateFields();
    } catch {
      return; // Ant Design shows inline validation errors — just stop here
    }
    const payload = {
      ...values,
      policyDecisionDate: values.policyDecisionDate?.format('YYYY-MM-DD') ?? null,
      stopDecisionDate: values.stopDecisionDate?.format('YYYY-MM-DD') ?? null,
    };

    if (mode === 'create') {
      createMutation.mutate(payload, {
        onSuccess: (data) => {
          message.success('Tạo dự án thành công');
          onSaved?.();
          onProjectCreated?.(data.id);
          navigate({ to: `/domestic-projects/${data.id}/edit` });
        },
        onError: () => message.error('Tạo dự án thất bại'),
      });
    } else {
      updateMutation.mutate(
        { id: projectId!, rowVersion: project!.rowVersion, ...payload },
        {
          onSuccess: () => { message.success('Cập nhật thành công'); onSaved?.(); },
          onError: () => message.error('Cập nhật thất bại'),
        },
      );
    }
  }

  // Reusable zone title style — purple left border
  const zoneTitle = (text: string) => (
    <div style={{ borderLeft: '4px solid #5B21B6', paddingLeft: 12, marginBottom: 16 }}>
      <h3 style={{ margin: 0, fontWeight: 700, textTransform: 'uppercase', color: '#1e293b', fontSize: 13, letterSpacing: '0.04em' }}>
        {text}
      </h3>
    </div>
  );

  return (
    <div>
      <Form form={form} layout="vertical" disabled={isReadonly} onValuesChange={() => onDirty?.()}>

        {/* Zone 1: Thông tin cơ bản & Pháp lý */}
        <div style={{ background: '#fff', border: '1px solid #f0f0f0', borderRadius: 8, padding: '20px 24px', marginBottom: 16 }}>
          {zoneTitle('Thông tin cơ bản & Pháp lý')}

          {/* projectCode hidden — auto-generated by BE; still submitted in form values */}
          <Form.Item name="projectCode" hidden>
            <Input />
          </Form.Item>

          {/* Tên dự án — full width */}
          <Row gutter={16}>
            <Col span={24}>
              <Form.Item name="projectName" label={<span>Tên dự án <span style={{ color: '#ff4d4f' }}>*</span></span>} rules={[{ required: true, message: 'Vui lòng nhập tên dự án' }]}>
                <Input placeholder="Nhập tên dự án" />
              </Form.Item>
            </Col>
          </Row>

          {/* QĐ chủ trương đầu tư file upload */}
          <Row gutter={16}>
            <Col span={24}>
              <Form.Item name="policyDecisionFileId" label="Quyết định chủ trương đầu tư (nếu có)">
                <FileUploadField accept=".pdf,.doc,.docx" maxCount={1} disabled={isReadonly} />
              </Form.Item>
            </Col>
          </Row>

          {/* 4 QĐ fields in one row */}
          <Row gutter={16} align="bottom">
            <Col span={6}>
              <Form.Item name="policyDecisionNumber" label={<span>Số quyết định <span style={{ color: '#ff4d4f' }}>*</span></span>}>
                <Input placeholder="VD: 88/QĐ-TTg" />
              </Form.Item>
            </Col>
            <Col span={6}>
              <Form.Item name="policyDecisionDate" label={<span>Ngày quyết định <span style={{ color: '#ff4d4f' }}>*</span></span>}>
                <DatePickerMaxToday placeholder="dd/mm/yyyy" style={{ width: '100%' }} />
              </Form.Item>
            </Col>
            <Col span={6}>
              <Form.Item name="policyDecisionAuthority" label={<span>Cơ quan quyết định <span style={{ color: '#ff4d4f' }}>*</span></span>}>
                <Input placeholder="Cơ quan quyết định" />
              </Form.Item>
            </Col>
            <Col span={6}>
              <Form.Item name="policyDecisionPerson" label={<span>Người quyết định <span style={{ color: '#ff4d4f' }}>*</span></span>}>
                <Input placeholder="Người quyết định" />
              </Form.Item>
            </Col>
          </Row>
        </div>

        {/* Zone 2: Tổng mức ĐT & Cơ cấu nguồn vốn */}
        <div style={{ background: '#fff', border: '1px solid #f0f0f0', borderRadius: 8, padding: '20px 24px', marginBottom: 16 }}>
          {zoneTitle('Tổng mức đầu tư & Cơ cấu nguồn vốn')}
          <Tab1Zone2Budget publicInvestment={publicInvestment} totalInvestment={totalInvestment} />
        </div>

        {/* Zone 3: Phân cấp & Chủ thể — purple-border div matching Zones 1 & 2 */}
        <div style={{ background: '#fff', border: '1px solid #f0f0f0', borderRadius: 8, padding: '20px 24px', marginBottom: 16 }}>
          {zoneTitle('Phân cấp & Chủ thể Quản lý')}
          <Tab1Zone3Classification
            industrySectors={industrySectors}
            projectGroups={projectGroups}
            statuses={statuses}
            managingAuthorities={managingAuthorities}
            nationalTargetPrograms={nationalTargetPrograms}
            projectOwners={projectOwners}
            pmus={pmus}
          />
        </div>
      </Form>

      {/* Zone 4: Địa điểm thực hiện — always visible per SRS mockup.
          When projectId exists: show inline table. When null (create mode): show placeholder. */}
      <div style={{ background: '#fff', border: '1px solid #f0f0f0', borderRadius: 8, padding: '20px 24px', marginBottom: 16 }}>
        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 0 }}>
          <div style={{ flex: 1 }}>
            {zoneTitle('Địa điểm thực hiện đầu tư')}
          </div>
          {projectId && !isReadonly && (
            <Button type="primary" icon={<PlusOutlined />} size="small" style={{ marginTop: 2 }}>
              Thêm địa điểm
            </Button>
          )}
        </div>
        {projectId ? (
          <Tab1LocationsZone projectId={projectId} disabled={isReadonly} />
        ) : (
          <div style={{ color: '#94a3b8', fontSize: 13, textAlign: 'center', padding: '16px 0' }}>
            Lưu thông tin dự án trước để thêm địa điểm thực hiện.
          </div>
        )}
      </div>

      {/* Zone 5: QĐ Đầu tư — always visible per SRS mockup.
          When projectId exists: fully interactive. When null (create mode): disabled placeholder state. */}
      <Tab1DecisionsZone projectId={projectId} disabled={isReadonly || !projectId} />

      {/* Action buttons — "Quay lại" (outline) left + "CẬP NHẬT" (blue primary) right, per SRS */}
      {!isReadonly && (
        <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 24, marginBottom: 8 }}>
          <Button
            onClick={() => navigate({ to: '/domestic-projects' })}
            style={{ height: 40, paddingLeft: 24, paddingRight: 24 }}
          >
            Quay lại
          </Button>
          <Button
            type="primary"
            onClick={handleSave}
            loading={saving}
            style={{ height: 40, paddingLeft: 32, paddingRight: 32, fontWeight: 600 }}
          >
            Cập nhật
          </Button>
        </div>
      )}
    </div>
  );
}
